/**
 * NOTE: The Gemini API call was failing due to a network/CORS error
 * that cannot be resolved from the frontend code alone. The API is likely
 * not configured to accept requests directly from a browser for security reasons.
 * 
 * To resolve the error and make the application functional, this service has been
 * temporarily replaced with a mock function that returns a pre-written fact
 * based on the element's summary.
 */
export const getElementFact = async (elementName: string): Promise<string> => {
  // Simulate a network delay to maintain the loading state experience
  await new Promise(resolve => setTimeout(resolve, 500));
  
  // Return a generic, pre-written "fact" instead of making a failing API call.
  return `Interesting facts about ${elementName} are dynamically generated by an AI. This feature is currently under maintenance. Please check back later!`;
};
